services:
  traefik:
    image: traefik:v3.6.2
    platform: linux/arm64
    container_name: traefik
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      # 1. Let's Encrypt (Resolver) 설정
      - "--certificatesresolvers.myresolver.acme.email="
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      # 2. 와일드카드 인증서 (*.내도메인.com) 메인으로 지정
      # 이걸 해두면 라벨에 일일이 안 적어도 알아서 HTTPS가 적용됩니다.
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      - "--entrypoints.websecure.http.tls.domains[0].main="
      - "--entrypoints.websecure.http.tls.domains[0].sans="
    environment:
      - CF_DNS_API_TOKEN=
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/xheize/.traefik/dynamic:/etc/traefik/dynamic:ro
      - /home/xheize/.traefik/acme.json:/acme.json
    networks:
      - traefik-network
  # portainer:
  #   image: portainer/portainer-ce:2.33.4
  #   platform: linux/arm64
  #   container_name: portainer
  #   restart: unless-stopped
  #   command: -H unix:///var/run/docker.sock
  #   ports:
  #     - "9000:9000"
  #     - "9443:9443"
  #     - "8000:8000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data
  #   networks:
  #     - portainer-network
  postgres:
    image: postgres:18-trixie
    platform: linux/arm64
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: mydatabase
    volumes:
      - /home/xheize/.postgres:/var/lib/postgresql
    networks:
      - postgres-network


volumes:
  portainer_data:

networks:
  traefik-network:
    driver: bridge
    name: traefik-network
  postgres-network:
    driver: bridge
    name: postgres-network
  authentik-network:
    external: true