services:
  reverse-proxy:
    image: nginx:latest
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/log:/var/log/nginx

# volumes:
#   db_data:
#   redis_data:
#   mqtt_data:
#   mqtt_log:

networks:
  default:
    driver: bridge